src/Entity/Reservation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReservationRepository")
 */
class Reservation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="reservations")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Parking", inversedBy="reservations")
     */
    private $parking;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Car", inversedBy="reservations")
     */
    private $car;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_start;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_end;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ParkingSpot", inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $spot;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getParking(): ?parking
    {
        return $this->parking;
    }

    public function setParking(?parking $parking): self
    {
        $this->parking = $parking;

        return $this;
    }

    public function getCar(): ?Car
    {
        return $this->car;
    }

    public function setCar(?Car $car): self
    {
        $this->car = $car;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(?\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(?\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getSpot(): ?ParkingSpot
    {
        return $this->spot;
    }

    public function setSpot(?ParkingSpot $spot): self
    {
        $this->spot = $spot;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_start')
            ->add('date_end')
            ->add('user')
            ->add('parking')
            ->add('spot')
            ->add('car')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/Back/ReservationController.php
<?php

namespace App\Controller\Back;

use App\Entity\Car;
use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Carbon\Carbon;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("back/reservation")
 */
class ReservationController extends AbstractController
{
    /**
     * @Route("/", name="reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $start = Carbon::instance($reservation->getDateStart());

            $days = $start->diffInDays($reservation->getDateEnd())+1;

            $price = $reservation->getParking()->getPrice() * $days;

            $reservation->setPrix($price);

            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $start = Carbon::instance($reservation->getDateStart());

            $days = $start->diffInDays($reservation->getDateEnd())+1;

            $price = $reservation->getParking()->getPrice() * $days;

            $reservation->setPrix($price);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservation_index', [
                'id' => $reservation->getId(),
            ]);
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index');
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/edit.html.twig
{% extends 'base_back.html.twig' %} {% block title %}Edit Reservation{% endblock
%} {% block body %}
<h1>Edit Reservation</h1>

{{ include("reservation/_form.html.twig", { button_label: "Update" }) }}

<a href="{{ path('reservation_index') }}">back to list</a>

{{ include("reservation/_delete_form.html.twig") }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base_back.html.twig' %} {% block title %}Reservation index{%
endblock %} {% block body %}
<h1>Reservation index</h1>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Date_start</th>
      <th>Date_end</th>
      <th>Place de parking</th>
      <th>Prix</th>
      <th>actions</th>
    </tr>
  </thead>
  <tbody>
    {% for reservation in reservations %}
    <tr>
      <td>{{ reservation.id }}</td>
      <td>
        {{ reservation.dateStart ? reservation.dateStart|date('Y-m-d') : '' }}
      </td>
      <td>
        {{ reservation.dateEnd ? reservation.dateEnd|date('Y-m-d') : '' }}
      </td>
      <td>{{ reservation.spot.code }}</td>
      <td>{{ reservation.prix }} EUR</td>
      <td>
        <a href="{{ path('reservation_show', { id: reservation.id }) }}"
          >show</a
        >
        <a href="{{ path('reservation_edit', { id: reservation.id }) }}"
          >edit</a
        >
      </td>
    </tr>
    {% else %}
    <tr>
      <td colspan="6">no records found</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{{ path('reservation_new') }}">Ajouter</a>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base_back.html.twig' %} {% block title %}New Reservation{% endblock
%} {% block body %}
<h1>Create new Reservation</h1>

{{ include("reservation/_form.html.twig") }}

<a href="{{ path('reservation_index') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base_back.html.twig' %} {% block title %}Reservation{% endblock %}
{% block body %}
<h1>Reservation</h1>

<table class="table">
  <tbody>
    <tr>
      <th>Id</th>
      <td>{{ reservation.id }}</td>
    </tr>
    <tr>
      <th>Date_start</th>
      <td>
        {{ reservation.dateStart ? reservation.dateStart|date('Y-m-d') : '' }}
      </td>
    </tr>
    <tr>
      <th>Date_end</th>
      <td>
        {{ reservation.dateEnd ? reservation.dateEnd|date('Y-m-d') : '' }}
      </td>
    </tr>
    <tr>
      <th>Prix</th>
      <td>{{ reservation.prix }} EUR</td>
    </tr>
  </tbody>
</table>

<a href="{{ path('reservation_index') }}">back to list</a>

<a href="{{ path('reservation_edit', { id: reservation.id }) }}">edit</a>

{{ include("reservation/_delete_form.html.twig") }}
{% endblock %}